# Développé par Ayato__#0069

# Explication du plugin :
# Ce plugin permet de créer des items de n'importe quel matériau
# et de les personnaliser à votre guise.

# Customisation des items :
# Pour personnaliser un item, il faut le créer dans le fichier Config.yml
# voici un exemple :
items: # haut du fichier, ne pas toucher
  ancientsword: # nom de l'item, quand vous voudrez vous le give il faudra mettre ce nom
    material: DIAMOND_SWORD # matériau de l'item, il faut mettre le nom du matériau sous le format de développement spigot (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
    name: "§9§l✻ Epée Ancienne ✻" # nom affiché de l'item, vous pouvez mettre des couleurs et des charactères spéciaux
    infinite: true # si vous voulez que l'item revienne après la mort, mettez true, sinon false
    unbreakable: false # si vous voulez que l'item ait une durabilité infinie, mettez true, sinon false
    lore: # description de l'item, vous pouvez mettre des couleurs et des charactères spéciaux
      - "§f§m-*---------------------------------*-"
      - "§c✯✯✯§7✯✯ §e§lRARE"
      - ""
      - "§7Cette §9épée rouillée §7vous"
      - "§7assistera dans vos §9duels §7!"
      - ""
      - "§9» §7Propriétaire: §9§l%owner%"
      - ""
      - "§c§l✗ §cCassable"
      - "§a§l✓ §aInfini"
      - "§f§m-*---------------------------------*-"
    enchantments: # enchantements de l'item, vous pouvez mettre des enchantements de n'importe quel niveau (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html)
      - "DAMAGE_ALL:5"
      - "FIRE_ASPECT:2"
      - "DURABILITY:3"

# Différents "placeholders" sont disponibles, vous pouvez les utiliser dans la description de l'item uniquement
#
# %owner% : nom du propriétaire de l'item
# %kills% : nombre de kills de l'item
# %lastkill% : nom du dernier joueur tué par l'item
# %damage_dealt% : nombre de dégâts infligés par l'item -> nécessite l'ajout d'un paramètre "countdamage: true" avant la description de l'item
# %blocks_broken% : nombre de blocs cassés par l'item -> nécessite l'ajout d'un paramètre "breakblock: true" avant la description de l'item

# Attributs spéciaux :
#
# Vous pouvez ajouter des attributs spéciaux à vos items, voici la liste des attributs disponibles :
# breakblock: true -> permet d'activer le compteur du nombre de blocs cassés par l'item
# countdamage: true -> permet d'activer le compteur du nombre de dégâts infligés par l'item
# thor: true -> permet à l'item de faire un apparait un éclair au clic droit
#     --> nécessite ensuite | thor-cooldown: <temps en secondes> -> pour définir le temps de recharge de l'éclair
# nofall: true -> donne au joueur l'effet nofall (ne pas prendre de dégâts en tombant) !!! UNIQUEMENT SUR LES ARMURES PORTÉES !!!
# effects: true -> permet d'ajouter des effets de potion à l'item
#     --> nécessite ensuite | effects-type: <armor/hand> -> pour définir si l'effet est appliqué sur une armure portée ou si le joueur tient l'item en main
#     --> nécessite ensuite | effects-list: <effect:amplifier> -> pour définir la liste des effets de potion (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html)
# EXEMPLE pour une épée donnant force 1 lorsqu'on la tient en main :
# effects: true
# effects-type: hand
# effects-list:
#   - "INCREASE_DAMAGE:0"