items:
  bow:
    material: BOW
    name: "§b❃ §b§lArc Antique §b❃"
    infinite: true
    unbreakable: true
    lore:
      - ""
      - "§f➥ §eCet §bArc §eancien"
      - "§f➥ §erevient dans §bl'inventaire"
      - "§f➥ §eaprès §bla mort §ede son guerrier !"
      - ""
      - "§f⦁ §bPropriétaire: §d%owner%"
      - "§f⦁ §bVictimes: §d%kills%"
      - "§f⦁ §bRareté §f» §c✯✯✯✯§f✯"
    enchantments:
      - "ARROW_INFINITE:1"
      - "ARROW_KNOCKBACK:2"
  sword:
    material: DIAMOND_SWORD
    name: "§b❃ §b§lEpée Antique §b❃"
    infinite: true
    unbreakable: true
    lore:
      - ""
      - "§f➥ §eCette §bEpée §eancienne"
      - "§f➥ §erevient dans §bl'inventaire"
      - "§f➥ §eaprès §bla mort §ede son guerrier !"
      - ""
      - "§f⦁ §bPropriétaire: §d%owner%"
      - "§f⦁ §bVictimes: §d%kills%"
      - "§f⦁ §bRareté §f» §c✯✯✯✯§f✯"
    enchantments:
      - "DAMAGE_ALL:5"
      - "FIRE_ASPECT:2"
  rod:
    material: FISHING_ROD
    name: "§b❃ §b§lRod Antique §b❃"
    infinite: true
    unbreakable: false
    lore:
      - ""
      - "§f➥ §eCette §bRod §eancienne"
      - "§f➥ §erevient dans §bl'inventaire"
      - "§f➥ §eaprès §bla mort §ede son guerrier !"
      - ""
      - "§f⦁ §bPropriétaire: §d%owner%"
      - "§f⦁ §bVictimes: §d%kills%"
      - "§f⦁ §bRareté §f» §c✯✯✯✯§f✯"
    enchantments:
  rod2:
    material: FISHING_ROD
    name: "§b❃ §b§lRod Antique §b❃"
    infinite: false
    unbreakable: false
    lore:
      - ""
      - "§f➥ §eCette §bRod §eancienne"
      - "§f➥ §erevient dans §bl'inventaire"
      - "§f➥ §eaprès §bla mort §ede son guerrier !"
      - ""
      - "§f⦁ §bPropriétaire: §d%owner%"
      - "§f⦁ §bVictimes: §d%kills%"
      - "§f⦁ §bRareté §f» §c✯✯✯✯§f✯"
    enchantments: